# Generated by Django 2.2.4 on 2022-02-01 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20220201_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='university',
            new_name='degree',
        ),
    ]
