# Generated by Django 2.2.4 on 2022-02-01 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20220201_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='degree',
        ),
        migrations.AddField(
            model_name='courses',
            name='university',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Education', to_field='university'),
        ),
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
