# Generated by Django 2.2.4 on 2022-02-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20220201_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydetail',
            name='phone2',
            field=models.CharField(max_length=50),
        ),
    ]
