# Generated by Django 2.2.4 on 2022-02-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20220201_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_type',
            name='type',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
