# Generated by Django 2.2.4 on 2022-02-01 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20220201_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post_type',
            options={'verbose_name_plural': 'Post Types'},
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post_Type', to_field='type'),
        ),
        migrations.AlterField(
            model_name='post_type',
            name='type',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
