# Generated by Django 2.2.4 on 2022-02-01 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20220201_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post_Type', to_field='type', verbose_name='type'),
        ),
    ]
