# Generated by Django 2.2.4 on 2022-02-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20220201_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydetail',
            name='phone2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
