# Generated by Django 2.2.4 on 2022-02-01 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_auto_20220201_1709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personal_Statement',
        ),
        migrations.DeleteModel(
            name='UoB_Year_1',
        ),
        migrations.DeleteModel(
            name='UoB_Year_2',
        ),
        migrations.DeleteModel(
            name='UoB_Year_3',
        ),
    ]
