# Generated by Django 2.2.4 on 2022-02-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_auto_20220201_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydetail',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
