# Generated by Django 2.2.4 on 2022-02-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_auto_20220201_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydetail',
            name='address',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
