# Generated by Django 2.2.4 on 2022-02-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_auto_20220201_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydetail',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
