# Generated by Django 2.2.4 on 2022-02-01 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_auto_20220201_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='degree',
        ),
    ]
