# Generated by Django 2.2.4 on 2022-02-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_auto_20220201_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
